language: generic
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      install: eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script: swift test
      
    - os: osx
      osx_image: xcode9
      dist: trusty
      sudo: required
      env: COCOAPODS_DISABLE_STATS=true ACTION=test  PLATFORM=Mac     DESTINATION='platform=OS X'
      script: set -o pipefail && pod install --repo-update && xcodebuild -workspace HttpSwift.xcworkspace -scheme HttpSwift -destination "$DESTINATION" $ACTION | xcpretty

    - os: osx
      osx_image: xcode9
      dist: trusty
      sudo: required
      env: COCOAPODS_DISABLE_STATS=true ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 6S'
      script: set -o pipefail && pod install --repo-update && xcodebuild -workspace HttpSwift.xcworkspace -scheme HttpSwift -destination "$DESTINATION" $ACTION | xcpretty

    - os: osx
      osx_image: xcode9
      dist: trusty
      sudo: required
      env: COCOAPODS_DISABLE_STATS=true ACTION=test  PLATFORM=tvOS    DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p'
      script: set -o pipefail && pod install --repo-update && xcodebuild -workspace HttpSwift.xcworkspace -scheme HttpSwift -destination "$DESTINATION" $ACTION | xcpretty

